1667811222547	Sync.LogManager	DEBUG	Flushing file log
1667811222554	Sync.LogManager	DEBUG	Log cleanup threshold time: 1666947222554
1667811222559	Sync.LogManager	DEBUG	Done deleting files.
1667811295416	Sync.SyncScheduler	DEBUG	Going to sleep, doing a quick sync.
1667811295417	Sync.Service	DEBUG	User-Agent: Firefox/97.0 (Linux x86_64) FxSync/1.99.0.20220202182137.desktop
1667811295417	Sync.Service	INFO	Starting sync at 2022-11-07 11:54:55 in browser session IjypUqZzJ7Dm
1667811295417	Sync.SyncScheduler	DEBUG	Clearing sync triggers and the global score.
1667811295420	Sync.Status	INFO	Resetting Status.
1667811295420	Sync.Status	DEBUG	Status.service: error.sync.failed => success.status_ok
1667811295422	FirefoxAccounts	DEBUG	FxAccountsProfileClient: Requested profile
1667811295422	FirefoxAccounts	DEBUG	getOAuthToken enter
1667811295423	FirefoxAccounts	TRACE	getCachedToken returning cached token
1667811295423	FirefoxAccounts	DEBUG	getOAuthToken returning a cached token
1667811295423	Services.Common.RESTRequest	DEBUG	GET request to https://profile.accounts.firefox.com/v1/profile
1667811295467	Services.Common.RESTRequest	DEBUG	GET https://profile.accounts.firefox.com/v1/profile failed: 2152398878 - NS_ERROR_UNKNOWN_HOST
1667811295467	FirefoxAccounts	ERROR	Background refresh of profile failed: {"name":"FxAccountsProfileClientError","code":null,"errno":998,"error":"NETWORK_ERROR","message":"[Exception... \"NS_ERROR_UNKNOWN_HOST\"  nsresult: \"0x804b001e (NS_ERROR_UNKNOWN_HOST)\"  location: \"JS frame :: resource://services-common/rest.js :: onStopRequest :: line 488\"  data: no]"}
1667811295469	Sync.Resource	WARN	GET request to https://sync-1-us-west1-g.sync.services.mozilla.com/1.5/200914463/info/collections?v=1.99.0 failed: [Exception... "The lookup of the hostname failed"  nsresult: "0x804b001e (NS_ERROR_UNKNOWN_HOST)"  location: "<unknown>"  data: no] No traceback available
1667811295469	Sync.Status	DEBUG	Status.sync: success.sync => error.login.reason.network
1667811295469	Sync.Status	DEBUG	Status.service: success.status_ok => error.sync.failed
1667811295469	Sync.ErrorHandler	ERROR	Sync encountered an error: [Exception... "The lookup of the hostname failed"  nsresult: "0x804b001e (NS_ERROR_UNKNOWN_HOST)"  location: "<unknown>"  data: no] No traceback available
1667811295469	Sync.SyncScheduler	DEBUG	Next sync in 3600000 ms. (why=reschedule)
1667811295472	Sync.Service	DEBUG	Exception calling anonymous function: [Exception... "The lookup of the hostname failed"  nsresult: "0x804b001e (NS_ERROR_UNKNOWN_HOST)"  location: "<unknown>"  data: no] No traceback available
