2022-11-16 14:42:02.010 [info] Starting worker process with pid 4122 (type: fileWatcher, window: 1).
2022-11-16 14:42:03.000 [error] [uncaught exception in sharedProcess]: Could not find pty on pty host: CodeExpectedError: Could not find pty on pty host
    at h._throwIfNoPty (/usr/share/code/resources/app/out/vs/platform/terminal/node/ptyHostMain.js:27:7199)
    at h.attachToProcess (/usr/share/code/resources/app/out/vs/platform/terminal/node/ptyHostMain.js:27:2712)
    at Object.call (/usr/share/code/resources/app/out/vs/platform/terminal/node/ptyHostMain.js:17:5858)
    at s.onPromise (/usr/share/code/resources/app/out/vs/platform/terminal/node/ptyHostMain.js:15:5833)
    at s.onRawMessage (/usr/share/code/resources/app/out/vs/platform/terminal/node/ptyHostMain.js:15:5216)
    at /usr/share/code/resources/app/out/vs/platform/terminal/node/ptyHostMain.js:15:4502
    at r.invoke (/usr/share/code/resources/app/out/vs/platform/terminal/node/ptyHostMain.js:11:145)
    at E.deliver (/usr/share/code/resources/app/out/vs/platform/terminal/node/ptyHostMain.js:11:2275)
    at w.fire (/usr/share/code/resources/app/out/vs/platform/terminal/node/ptyHostMain.js:11:1853)
    at process.O (/usr/share/code/resources/app/out/vs/platform/terminal/node/ptyHostMain.js:9:21066)
    at process.emit (node:events:526:28)
    at emit (node:internal/child_process:938:14)
    at process.processTicksAndRejections (node:internal/process/task_queues:84:21)
